name: 'shellcheck'

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "*"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
        SHELLCHECK_OPTS: -s sh